name = "so4-keeper"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true
invocation_logs = true

[vars]
ORACLE_WORKER_URL = "https://oracle.biscotti-proxy-worker.workers.dev"
RPC_URL = "https://soroban-testnet.stellar.org"
ORACLE_CONTRACT = "CBEMTV23SIJJBIST3V5HTMWHR4MHYGHNBIG4M26U4LGUJTWZXTFSVQEY"
ORDER_HANDLER = "CC35OFZVWUTAZPV3B6UKSDVAVORZEWUUMOMTHO33H4YR4C5FKPEFODKY"
DEPOSIT_HANDLER = "CDWOFIP4YQJGMCYAOWLSRBAWN2OTJUG2I5WOFC32O2TX2SRU56RWBE5C"
WITHDRAWAL_HANDLER = "CCA5HRHMG6E6BVYRICSLZ5CK5KNPAAKXQ7XWDM34WWVGNHWHA26GRVVE"
READER_CONTRACT = "CC6OZUHF3LVO6PNP3V2EB36ORB3YSVYSH3LWD3RFLO4NUO3BYCXSWSYC"
DATA_STORE = "CCZ3VKBEDLNBO2JM3EXL3SNBDJOV5BTN52FVQPER7F6D5GCE53PITQ3J"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

[triggers]
crons = ["*/1 * * * *"]

[[services]]
binding = "ORACLE_SERVICE"
service = "oracle"
